---
# tasks file for devtools
- name: Install other packages
  become: yes
  apt:
    name:
      - vim
      - git
      - curl
      - build-essential
      - python3-venv
      - python3-pip
      - tree
      - neofetch
    state: present

- name: Install pip modules
  pip:
    name:
      - ansible-lint
      - yamllint
      - psutil
