---
# tasks file for devtools
- name: Install other packages
  block:
    - name: Install other packages
      apt:
        name:
          - vim
          - git
          - curl
          - build-essential
          - python3-venv
          - python3-pip
          - tree
        state: present

    - name: Check if chrome is installed
      command: 'which google-chrome'
      register: google_chrome_installed
      ignore_errors: yes
      changed_when: no

    - name: Install Chrome
      apt:
        deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      when: google_chrome_installed.rc != 0
  become: yes
  