---
# tasks file for jetbrains
- name: Check if Toolbox is installed
  stat:
    path: ~/.local/share/JetBrains/Toolbox
  register: toolbox_installed
  changed_when: no

- name: Install ToolBoox
  block:
    - name: Find latest JetbrainsToolbox release
      uri:
        url: https://data.services.jetbrains.com/products/releases?code=TBA&latest=true&type=release
        return_content: yes
        body_format: json
        follow_redirects: all
      register: jt_releases

    - name: Download the tar.gz installer
      get_url:
        url: "{{ jt_releases.json.TBA.0.downloads.linux.link }}"
        dest: /tmp/jetbrains

    - name: Extract JetBrainsToolbox
      unarchive:
        src: /tmp/jetbrains
        dest: /tmp
        remote_src: yes
        list_files: yes
      register: jt_extracted

    - name: Install JetBrainsToolbox
      command:
        cmd: ./jetbrains-toolbox
        chdir: "/tmp/{{ jt_extracted.files.0 }}"
      when: not jt_extracted.failed
  when: not toolbox_installed.stat.exists
