---
# tasks file for chrome
- name: Check if chrome is installed
  command: 'which google-chrome'
  register: google_chrome_installed
  ignore_errors: yes
  changed_when: no

- name: Install Chrome
  become: yes
  apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  when: google_chrome_installed.rc != 0
