---
# tasks file for teams
- name: Check if teams is installed
  command: 'which teams'
  register: teams_installed
  ignore_errors: yes
  changed_when: no

- name: Install Teams
  apt:
    deb: https://go.microsoft.com/fwlink/p/?LinkID=2112886&culture=en-us&country=WW
  become: yes
  when: teams_installed.rc != 0
