---
# tasks file for lenovo
- name: Check if ideapad-laptop is blacklisted
  stat:
    path: /etc/modprobe.d/blacklist-ideapad-laptop.conf
  register: ideapad
  changed_when: no

- name: Install ToolBoox
  block:
    - name: Create blacklist file
      copy:
        mode: '0644'
        dest: /etc/modprobe.d/blacklist-ideapad-laptop.conf
        content: |
          blacklist ideapad-laptop
    - name: Update initramfs
      command: update-initramfs -u
  become: yes
  when: not ideapad.stat.exists
