---
# launch all roles
- name: Debian Postinstall
  gather_facts: no
  hosts: all
  roles:
    - ../roles/upgrade
    - ../roles/devtools
    - ../roles/gnome
    - ../roles/code
    - ../roles/chrome
    - ../roles/jetbrains
    - ../roles/nvidia
    - ../roles/lenovo
