name: Ansible Galaxy

on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Inject a dynamic Collection version
      uses: artis3n/ansible_galaxy_collection@v2.2.3
      with:
        api_key: '${{ secrets.GALAXY_API_KEY }}'
        galaxy_version: '${{ env.GITHUB_REF }}'
