name: Ansible Galaxy

on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Get the version from the tag
      run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF/refs\/tags\//

    - name: Inject a dynamic Collection version
      uses: artis3n/ansible_galaxy_collection@v2.2.3
      with:
        api_key: '${{ secrets.GALAXY_API_KEY }}'
        galaxy_version: '${{ env.RELEASE_VERSION }}'
